### ISSUE TITLE
-> Working SSL Client example here <-

### ISSUE THREAD

**Issue by Maexel** [zaphoyd/websocketpp#706]
Hello,

i havent found an example for an working client with ssl, but i was able to create a working client by myself today.
Basically it is just the echo client code where i activated tls and addet the tls init handler, but for people who aren't that familiar with c++ it will be really helpful and save time. 
Maybe someone wants to create a echo client tls in the examples dir from it :)

``/*
 * Copyright (c) 2016, Peter Thorson. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the WebSocket++ Project nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL PETER THORSON BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <websocketpp/config/asio_client.hpp>
#include <websocketpp/client.hpp>

#include <iostream>

typedef websocketpp::client<websocketpp::config::asio_tls_client> client;
typedef std::shared_ptr<boost::asio::ssl::context> context_ptr;
using websocketpp::lib::placeholders::_1;
using websocketpp::lib::placeholders::_2;
using websocketpp::lib::bind;

// pull out the type of messages sent by our config
typedef websocketpp::config::asio_client::message_type::ptr message_ptr;

// This message handler will be invoked once for each incoming message. It
// prints the message and then sends a copy of the message back to the server.
void on_message(client* c, websocketpp::connection_hdl hdl, message_ptr msg) {
    std::cout << "on_message called with hdl: " << hdl.lock().get()
              << " and message: " << msg->get_payload()
              << std::endl;

    websocketpp::lib::error_code ec;

    c->send(hdl, msg->get_payload(), msg->get_opcode(), ec);
    if (ec) {
        std::cout << "Echo failed because: " << ec.message() << std::endl;
    }
}

static context_ptr on_tls_init() {
    // establishes a SSL connection
    context_ptr ctx = std::make_shared<boost::asio::ssl::context>(boost::asio::ssl::context::sslv23);

    try {
        ctx->set_options(boost::asio::ssl::context::default_workarounds |
                         boost::asio::ssl::context::no_sslv2 |
                         boost::asio::ssl::context::no_sslv3 |
                         boost::asio::ssl::context::single_dh_use);
    } catch (std::exception &e) {
        std::cout << "Error in context pointer: " << e.what() << std::endl;
    }
    return ctx;
}

int main(int argc, char* argv[]) {
    // Create a client endpoint
    client c;

    std::string uri = "wss://localhost";

    if (argc == 2) {
        uri = argv[1];
    }

    try {
        // Set logging to be pretty verbose (everything except message payloads)
        c.set_access_channels(websocketpp::log::alevel::all);
        c.clear_access_channels(websocketpp::log::alevel::frame_payload);

        // Initialize ASIO
        c.init_asio();
        c.set_tls_init_handler(bind(&on_tls_init));

        // Register our message handler
        c.set_message_handler(bind(&on_message,&c,::_1,::_2));

        websocketpp::lib::error_code ec;
        client::connection_ptr con = c.get_connection(uri, ec);
        if (ec) {
            std::cout << "could not create connection because: " << ec.message() << std::endl;
            return 0;
        }

        // Note that connect here only requests a connection. No network messages are
        // exchanged until the event loop starts running in the next line.
        c.connect(con);

        // Start the ASIO io_service run loop
        // this will cause a single connection to be made to the server. c.run()
        // will exit when this connection is closed.
        c.run();
    } catch (websocketpp::exception const & e) {
        std::cout << e.what() << std::endl;
    }
}

**Comment by aharonamir** [comment]
:+1:  good example, but can't connect with this config to non-secure servers
Is there a good example for mixing secure/non-secure?

**Comment by hejian1639** [comment]
same question

**Comment by zaphoyd** [comment]
For mixed TLS/non TLS clients the procedure is similar to servers. I’ll see if I can prepare a client example that handles both secure and non-secure endpoints. In the meantime there is an echo_server_both example that demonstrates 95% of what is needed:

- make two endpoints, one with a TLS config, one without.
- open WSS urls on the TLS endpoint, open WS urls on the plain endpoint.
- both endpoints can run on the same io_service on the same thread without conflict.

**Comment by Sleepingbug** [comment]
Thank you all.
I've fixed my problem.

**Comment by logieestrada** [comment]
can you tell me what openssl version is required to get tls support going ?  will v1.0.2 work?

**Comment by br101** [comment]
Thanks a lot! This got me started with WebSocketPP

**Comment by Xeroxlaser** [comment]
Thanks, helpful

**Comment by Scott-Taiwan** [comment]
Dear Maexel,
the sample code seems to be a client, but after it's running, how can I enter some message into the terminal for sending to the other end?
do you have run example?

Thank you very much

Scott

**Comment by hzg0226** [comment]
Very wonderful example for tls-demo on websocketpp, thanks a lot!.

**Comment by Non-Unruly** [comment]
Awesome!

**Comment by clxye** [comment]
I also encountered the same problem and consulted a lot of information. Thank you very much!

**Comment by cotomonaga** [comment]
Thank you, Mr. Maexel!

I wrote a WebSocket client that supports TLS, based on Maexel's excellent code.

**a WebSocket client that supports TLS**
[https://github.com/cotomonaga/websocketpp_tutorial/blob/master/utility_client/step7.cpp](https://github.com/cotomonaga/websocketpp_tutorial/blob/master/utility_client/step7.cpp)

For those who have tried websocketpp's "Utility Client Example Application Tutorial", this code would be the answer to step7 "Using TLS / Secure WebSockets".

**Utility Client Example Application Tutorial**
[https://docs.websocketpp.org/md_tutorials_utility_client_utility_client.html](https://docs.websocketpp.org/md_tutorials_utility_client_utility_client.html)

If you are looking for a config to non-secure servers, the above tutorial will be helpful.

Thanks.

**Comment by sweihub** [comment]
This example crashes for me, any idea?
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3846452==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000018 (pc 0x7fb424a491b0 bp 0x60d000000228 sp 0x7ffee5191100 T0)
==3846452==The signal is caused by a READ memory access.
==3846452==Hint: address points to the zero page.
    #0 0x7fb424a491b0 in __pthread_rwlock_wrlock_full64 nptl/pthread_rwlock_common.c:603:7
    #1 0x7fb424a491b0 in pthread_rwlock_wrlock nptl/pthread_rwlock_wrlock.c:26:16
    #2 0x7fb4250d58a8 in CRYPTO_THREAD_write_lock (/home/swei/quant/trade/ctp/sdk/trade/unix.x86_64/libthosttraderapi_se.so+0x2d58a8) (BuildId: 108f03accbb650a1653226f059ddfd1ee88e53be)
    #3 0x7fb4250d58eb in CRYPTO_atomic_add (/home/swei/quant/trade/ctp/sdk/trade/unix.x86_64/libthosttraderapi_se.so+0x2d58eb) (BuildId: 108f03accbb650a1653226f059ddfd1ee88e53be)
    #4 0x7fb42505f6ca in BIO_up_ref (/home/swei/quant/trade/ctp/sdk/trade/unix.x86_64/libthosttraderapi_se.so+0x25f6ca) (BuildId: 108f03accbb650a1653226f059ddfd1ee88e53be)
    #5 0x7fb42502aacc in SSL_set_bio (/home/swei/quant/trade/ctp/sdk/trade/unix.x86_64/libthosttraderapi_se.so+0x22aacc) (BuildId: 108f03accbb650a1653226f059ddfd1ee88e53be)
    #6 0x563e8c7315c8 in boost::asio::ssl::detail::engine::engine(ssl_ctx_st*) /usr/include/boost/asio/ssl/detail/impl/engine.ipp:56:3
    #7 0x563e8c730d16 in boost::asio::ssl::detail::stream_core::stream_core<boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>>>(ssl_ctx_st*, boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>> const&) /usr/include/boost/asio/ssl/detail/stream_core.hpp:43:7
    #8 0x563e8c72f0b6 in boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0>>, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0>>>>>::stream<boost::asio::io_context&>(boost::asio::io_context&, boost::asio::ssl::context&) /usr/include/boost/asio/ssl/stream.hpp:101:7
    #9 0x563e8c72cc64 in websocketpp::transport::asio::tls_socket::connection::init_asio(boost::asio::io_context*, std::shared_ptr<boost::asio::io_context::strand>, bool) /home/swei/quant/trade/ctp/../core/include/websocketpp/transport/asio/security/tls.hpp:196:28
    #10 0x563e8c72beb7 in websocketpp::transport::asio::connection<websocketpp::config::asio_tls_client::transport_config>::init_asio(boost::asio::io_context*) /home/swei/quant/trade/ctp/../core/include/websocketpp/transport/asio/connection.hpp:468:47
    #11 0x563e8c6aa687 in websocketpp::transport::asio::endpoint<websocketpp::config::asio_tls_client::transport_config>::init(std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio_tls_client::transport_config>>) /home/swei/quant/trade/ctp/../core/include/websocketpp/transport/asio/endpoint.hpp:1122:20
    #12 0x563e8c6a8f27 in websocketpp::endpoint<websocketpp::connection<websocketpp::config::asio_tls_client>, websocketpp::config::asio_tls_client>::create_connection() /home/swei/quant/trade/ctp/../core/include/websocketpp/impl/endpoint_impl.hpp:86:26
    #13 0x563e8c6a3a0d in websocketpp::client<websocketpp::config::asio_tls_client>::get_connection(std::shared_ptr<websocketpp::uri>, std::error_code&) /home/swei/quant/trade/ctp/../core/include/websocketpp/roles/client_endpoint.hpp:95:45
    #14 0x563e8c61f448 in websocketpp::client<websocketpp::config::asio_tls_client>::get_connection(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::error_code&) /home/swei/quant/trade/ctp/../core/include/websocketpp/roles/client_endpoint.hpp:127:16
    #15 0x563e8c61922f in tls_test() /home/swei/quant/trade/ctp/src/tls_test.cpp:68:40
    #16 0x563e8c587635 in main /home/swei/quant/trade/ctp/src/main.cpp:69:5
    #17 0x7fb4249d7d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #18 0x7fb4249d7e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #19 0x563e8c33f4d4 in _start (/home/swei/quant/trade/ctp/build/ctp+0x744d4) (BuildId: b3dc8dc661022cd0f5e4442ae0f8ee3b8c2fda5f)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV nptl/pthread_rwlock_common.c:603:7 in __pthread_rwlock_wrlock_full64
==3846452==ABORTING
```
